version: '3.8'

services:
  django_gunicorn:
    volumes:
      - static:/static
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - DEBUG=${DEBUG}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}

    build:
      context: .
    ports:
      - "8000:8000"
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn
      
volumes:
  static: 