version: '3.8'

services:
  app:
    build:
      context: .
    volumes:
      - static_data:/vol/web
    environment:
      - SECRET_KEY=-nro!j**h$!c=d(*r30+u46g$^(oge1!*9ymb4v8ks9%mwyim%
      - ALLOWED_HOSTS=127.0.0.1,localhost

  proxy:
    build:
      context: ./proxy
    volumes:
      - static_data:/vol/static
    ports:
      - "8010:8010"
    depends_on:
      - app

volumes:
  static_data:
