# Generated by Django 3.1.7 on 2021-03-30 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date',
        ),
    ]
